Return-Path: admin@petromaz.ir
Received: from mail.petromaz.ir (LHLO mail.petromaz.ir) (10.3.153.2) by
 mail.petromaz.ir with LMTP; Tue, 12 Mar 2024 05:43:19 +0000 (UTC)
Received: from localhost.localdomain (mail.petromaz.ir [10.3.153.2])
	by mail.petromaz.ir (Postfix) with ESMTP id 86512C804E2
	for <admin@petromaz.ir>; Tue, 12 Mar 2024 05:43:19 +0000 (UTC)
To: admin@petromaz.ir
From: admin@petromaz.ir
Subject: Service zimlet stopped on mail.petromaz.ir
Message-Id: <20240312054319.86512C804E2@mail.petromaz.ir>
Date: Tue, 12 Mar 2024 05:43:19 +0000 (UTC)

Mar  6 20:06:11 localhost zmconfigd[12733]: Service status change: mail.petromaz.ir zimlet changed from running to stopped
