Return-Path: rezaee@petromaz.ir
Received: from mail.petromaz.ir (LHLO mail.petromaz.ir) (10.3.153.2) by
 mail.petromaz.ir with LMTP; Tue, 12 Mar 2024 05:43:14 +0000 (UTC)
Received: from [127.0.0.1] (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTPSA id 8A56E5E4DAF
	for <mansouri@petromaz.ir>; Wed,  6 Mar 2024 20:09:34 +0000 (UTC)
Content-Type: multipart/mixed; boundary="===============0799258120515277327=="
MIME-Version: 1.0
From: rezaee@petromaz.ir
To: mansouri@petromaz.ir
Subject: =?utf-8?b?2K/Ysdiu2YjYp9iz2Kog2K/Ys9iq2LHYs9uMINio2Ycg2LPYsdmI2LE=?=
Message-Id: <20240306200934.8A56E5E4DAF@mail.petromaz.ir>
Date: Wed,  6 Mar 2024 20:09:34 +0000 (UTC)

--===============0799258120515277327==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

2LPZhNin2YUK2YTYt9mB2Kcg2qnZhNuM2K8g2LnZhdmI2YXbjCDZhdix2Kcg2K/YsSDYs9ix2YjY
sSDYp9i22KfZgdmHINqp2YbbjNivINiq2Kcg2KjYqtmI2KfZhtmFINio2K/ZiNmGINm+2LPZiNix
2K8g2KjZhyDYotmGINmI2LXZhCDYtNmI2YUuCgpzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUVB
WE5RdE9kYjF5N08rN2VnT2tOaGZMMzd5VURESituTG5ZQm4wQ1drSVMwcEkvQjNrYVgrVWxNZWJi
VzZCRVd2cHFsTVh1VmhNTUVPRndUS0ROcE5vUXlhOGVnd1ptMXdMVkd5akI0NkZ0S0NiNDFxYXg3
VEVFcStEdzkveEdhS1dDSGlpN2xUTnl0NmZvZkI0dnAwRlhvMGpaeEdzdEdwM3ZtYmlyWG9IbkdT
aE13MFJSUEE2Q2lpMmxhcUJHbUZ5SWxGYmw5aU1Ea1pPQTJRK3JsMHlFUnFlYUlLOTBlcENsdXdV
eTB0eVlxRGxmeEF5c0RCd2hraGhCOWZTcjIrSUU5eDZaS2EyZVJrWTQ0UlhZTHZFcENFWlVKNWtW
MWM1WGkrVi8zblVzY1BxMmdUWHQrKzh1SUxvUjIzUG41NWdtMlJKRmo4M2Q4NDZyY1Q2R0F1dmJR
QUFBUUJmb1hrZitNeTkvTWFkcEJyOTlaRC9yZTR5VlczNmpsK1JmR3BTY0JSb01YNU5PWTNNSHJh
MjRzY29WaFpkUDR4Y0V0SHprbUx3NEVhb1dRWWNRTmJRS0g5elpwSHpwUTJtQ3c0Ukx6QkpydmFm
KzhVSVlrT0xabmRsSktuUVZkSVJyWWpUSG9Nc1FHZzd6TXJVSWRqdE1BQ21oUmxKN0Ztd3hQYjJ4
ZDhtV2tzcnQ4aDZoSTBtMVZsazhzVGdOa3BVY0hEeFlteTVwcExHRHYwUWxKNlZSbmNObWx2QTJF
N21EZS84TE52eTFzY0thdERDblpzTWtmZHRkcjJpTkM5QS8zdGNKeGdjTllQNTlwaTJFTFZhTDUx
WE1FcHk1RFBLQXJuaWtmdEMrR1doTzJHc2ZmS0ZvKzZYUTRZZlRvbU15QWR3aklUTW5OdVJvbC9s
WGpmLwo=

سلام
لطفا کلید عمومی مرا در سرور اضافه کنید تا بتوانم بدون پسورد به آن وصل شوم.

ssh-rsa AAAAB3NzaC1yc2EAAAEAXNQtOdb1y7O+7egOkNhfL37yUDDJ+nLnYBn0CWkIS0pI/B3kaX+UlMebbW6BEWvpqlMXuVhMMEOFwTKDNpNoQya8egwZm1wLVGyjB46FtKCb41qax7TEEq+Dw9/xGaKWCHii7lTNyt6fofB4vp0FXo0jZxGstGp3vmbirXoHnGShMw0RRPA6Cii2laqBGmFyIlFbl9iMDkZOA2Q+rl0yERqeaIK90epCluwUy0tyYqDlfxAysDBwhkhhB9fSr2+IE9x6ZKa2eRkY44RXYLvEpCEZUJ5kV1c5Xi+V/3nUscPq2gTXt++8uILoR23Pn55gm2RJFj83d846rcT6GAuvbQAAAQBfoXkf+My9/MadpBr99ZD/re4yVW36jl+RfGpScBRoMX5NOY3MHra24scoVhZdP4xcEtHzkmLw4EaoWQYcQNbQKH9zZpHzpQ2mCw4RLzBJrvaf+8UIYkOLZndlJKnQVdIRrYjTHoMsQGg7zMrUIdjtMACmhRlJ7FmwxPb2xd8mWksrt8h6hI0m1Vlk8sTgNkpUcHDxYmy5ppLGDv0QlJ6VRncNmlvA2E7mDe/8LNvy1scKatDCnZsMkfdtdr2iNC9A/3tcJxgcNYP59pi2ELVaL51XMEpy5DPKArnikftC+GWhO2GsffKFo+6XQ4YfTomMyAdwjITMnNuRol/lXjf/

--===============0799258120515277327==--
