Return-Path: mansouri@petromaz.ir
Received: from mail.petromaz.ir (LHLO mail.petromaz.ir) (10.3.153.2) by
 mail.petromaz.ir with LMTP; Tue, 12 Mar 2024 05:43:14 +0000 (UTC)
Received: from [127.0.0.1] (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTPSA id 9BB295E4DB3
	for <kolahi@petromaz.ir>; Wed,  6 Mar 2024 20:09:34 +0000 (UTC)
Content-Type: multipart/mixed; boundary="===============9002450830180494869=="
MIME-Version: 1.0
From: mansouri@petromaz.ir
To: kolahi@petromaz.ir
Subject: =?utf-8?b?2YHYp9uM2YQg2Kfaqdiz2YQ=?=
Message-Id: <20240306200934.9BB295E4DB3@mail.petromaz.ir>
Date: Wed,  6 Mar 2024 20:09:34 +0000 (UTC)

--===============9002450830180494869==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

2LPZhNin2YUK2YHYp9uM2YQg2Kfaqdiz2YTbjCDaqdmHINmE2KfYstmFINiv2KfYtNiq24zYryDY
sdinINit2K/Yp9qp2KvYsSDYqtinINmB2LHYr9inINin2LIg2LfYsduM2YIg2K/bjNiq2KfYr9uM
2YjYryDYqNix2KfbjNiq2KfZhiDYp9ix2LPYp9mEINmF24zigIzaqdmG2YUuCg==

سلام
فایل اکسلی که لازم داشتید را حداکثر تا فردا از طریق دیتادیود برایتان ارسال می‌کنم.

--===============9002450830180494869==--
