Return-Path: rezaee@petromaz.ir
Received: from mail.petromaz.ir (LHLO mail.petromaz.ir) (10.3.153.2) by
 mail.petromaz.ir with LMTP; Tue, 12 Mar 2024 05:43:14 +0000 (UTC)
Received: from [127.0.0.1] (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTPSA id AD26D5E4DB8
	for <pirouz@petromaz.ir>; Wed,  6 Mar 2024 20:09:34 +0000 (UTC)
Content-Type: multipart/mixed; boundary="===============1445745860374015200=="
MIME-Version: 1.0
From: rezaee@petromaz.ir
To: pirouz@petromaz.ir
Subject: =?utf-8?b?2YHYp9uM2YQg2b7Yp9uM2KrZiNmGINin2LPaqdin2K/Ypw==?=
Message-Id: <20240306200934.AD26D5E4DB8@mail.petromaz.ir>
Date: Wed,  6 Mar 2024 20:09:34 +0000 (UTC)

--===============1445745860374015200==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

2LPZhNin2YUg2KjZhyDZhti42LEg2YXbjNix2LPZhyDaqdivINin2LPaqdin2K/YpyDbjNmHINio
2Kfar9uMINiv2KfYsdmH2Iwg2YTYt9mB2Kcg2YHYp9uM2YQg2b7Yp9uM2KrZiNmG2LQg2LHYpyDb
jNmHINio2LHYsdiz24wg2KjaqdmG

سلام به نظر میرسه کد اسکادا یه باگی داره، لطفا فایل پایتونش را یه بررسی بکن

--===============1445745860374015200==
Content-Type: application/octet-stream; Name="email6/scada-source.tar.xz"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="email6/scada-source.tar.xz"

/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4An/AcNdADCcLFxwPiqFF3/dlnTUUdWK52DKNYmnvUQo
tCChMKhB/GvaHC2kyfXMR1xFOVmbnMZpbGaKKzAGonsP+WYk5p4cCcTbgtwKOyk9rEhcdTUQmtDC
deCrV6IYtZOj3/dEbb9jPCu7jg/9Kr2xHwaJD6qHghJTiOGjA2zTK9X7bm5cxfueSNiOFNmCQayH
6Qle2idzRMplPVG5RSuORJ0EESZ4VQE5X86k0RhaV8KV+i77nmLlCaz0X5L/FcMwrGZMkshuLwhP
o8ssZ+FVWi8Cx6k0ed8yYkoE5XTkoxvjAAwfxkT+AItWPFMGbKy29BGNcmp5Fw9MpPA1q3C3DMej
fClO/ASXfkIloHTBwfjyyBOF9C5da0CfFYPvyPsw7RmflXY3F0Vv/4RIvgIWCHdvxx83Xwp2gLKS
8g43Fto0oQYbxvo5ujE3TBlwKDp/4x8qmkMxGvUoA7cDg4B1UzlxZeTVKRoLu2EXMMgc1WiF+gGQ
6wSWUrfeA26DZlRFh2aKuc0YipRv4TTY5dG4c1p65eBVeJXo3+WkbkPSyaH55ctctqVO33/4w6Rn
A5rhQV+BC1pSj6ATtRCFAw2j20DpeqZZPwAAAOoOrDK+juxwAAHfA4AUAABgveuRscRn+wIAAAAA
BFla

--===============1445745860374015200==--
